export const data = [
    {
        id:1,
        category: 'skincare',
        productName:'Kit masage facial',
        description: 'Este kit incluye un rodillo facial, una gua sha y un gel de aloe vera para acompañar tu masage facial',
        price: 899,
        urlImg:'https://images.unsplash.com/photo-1600428853876-fb5a850b444f?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        quantity: 1,
    },
    {
        id:2,
        category: 'skincare',
        productName:'Masajeador Facial',
        description: 'Este dispositivo de rejuvenecimiento facial funciona con microcorrientes que disminuyen las lineas de expresion y la flacides facial',
        price: 480,
        urlImg:'https://images.unsplash.com/photo-1600428853876-fb5a850b444f?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        quantity: 1,
    },
    {
        id:3,
        category: 'skincare',
        productName:'Serum piel seca',
        description: 'Este serum aporta a tu piel la humectacion e hidratacion necesaria por 24 horas. usalo en el dia y en la noche',
        price: 380,
        urlImg:'https://images.unsplash.com/photo-1600428853876-fb5a850b444f?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        quantity: 1,
    },
    {
        id:4,
        category: 'skincare',
        productName:'Serum piel mixta',
        description: 'Este serum es ideal para todo tipo de piel, retiene la humectacion de tu piel sin sensacion oleosa o grasosa',
        price: 380,
        urlImg:'https://images.unsplash.com/photo-1600428853876-fb5a850b444f?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        quantity: 1,
    },
    {
        id:5,
        category: 'uñas',
        productName:'Kit gelish',
        description:'Este kit incluye, esmalte base para uñas, ablandador de cutículas, 3 esmaltes de uñas en gel en distintos tonos y una lampara especial para secar nuestros esmaltes de gel. Todo lo necesario para que comienzes a embellecer tus uñas desde la comodidad de tu casa',
        price: 2399,
        urlImg:'https://images.unsplash.com/photo-1599948128020-9a44505b0d1b?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        quantity: 1,
    },
    {
        id:6,
        category: 'uñas',
        productName:'Ablandador de cutícula',
        description: 'Aceite hecho a base de productos naturales. Ayuda a suavizar la cutícula de tus uñas y favorece un desarrollo saludable de la misma',
        price: 119,
        urlImg:'https://images.unsplash.com/photo-1599948128020-9a44505b0d1b?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        quantity: 1,
    },
    {
        id:7,
        category: 'uñas',
        productName:'Kit esmaltes',
        description:'Caja con nuestros 5 colores mas vendidos de esmaltes en gel',
        price: 480,
        urlImg:'https://images.unsplash.com/photo-1599948128020-9a44505b0d1b?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        quantity: 1,
    },
    {
        id:8,
        category: 'depilacion',
        productName:'Cera depiladora',
        description: 'Cera para depilar hecha a base de cera natural de abejas. No irrita la piel. No necesita tela para retirarse. Calentar en el microondas por 5 minutos o hasta que este totalmente liquida, esperar de 1 a 2 minutos antes de aplicar en la piel limpia',
        price: 299,
        urlImg:'https://images.pexels.com/photos/7796229/pexels-photo-7796229.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        quantity: 1,
    },
    {
        id:9,
        category: 'depilacion',
        productName:'Agua de Rosas',
        description: 'Aplica despues de depilar con cera para restaurar la piel e hidratarla',
        price: 299,
        urlImg:'https://images.pexels.com/photos/17466121/pexels-photo-17466121/free-photo-of-lujo-rosas-salud-tratamiento.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        quantity: 1,
    },
    {
        id:10,
        category: 'depilacion',
        productName:'Exfoliante pre',
        description: 'Exfolia tu piel antes de depilarla para obtener un resultado homogeneo y sin vellitos enterrados',
        price: 399,
        urlImg:'https://images.pexels.com/photos/4857811/pexels-photo-4857811.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        quantity: 1,
    },

];